Added if check for less than php8 with libxml_disable_entity_loader function
Currence-Online/iDIN-libraries-php pull request #14
Opened 2021-01-06 12:37 UTC by DHouweling

2021-01-06 12:41 UTC, BertvanHoekelen requested changes
Also add php 8.0 to composer.json

2021-01-06 12:41 UTC, BertvanHoekelen commented on .gitignore
> +.idea/
This should not be added to the repo but should be [ignored globally](https://stackoverflow.com/questions/59328900/how-to-globally-ignore-the-idea-folder-in-git-not-just-adding-it-to-gitignor).

2021-01-06 12:41 UTC, BertvanHoekelen commented on library/AuthenticationResponse.php
> +        }
```suggestion
        if (\PHP_VERSION_ID < 80000) {
            $oldValue = libxml_disable_entity_loader(true);
        }

```

2021-01-06 12:41 UTC, BertvanHoekelen commented on library/DirectoryResponse.php
> +        }
```suggestion
        }

```

2021-01-06 12:41 UTC, BertvanHoekelen commented on library/StatusResponse.php
> +        }
```suggestion
        }

```

2021-01-06 12:41 UTC, BertvanHoekelen commented on library/XmlProcessor.php
> +        }
```suggestion
        }

```

2021-01-06 12:41 UTC, BertvanHoekelen commented on library/XmlProcessor.php
> +        }
```suggestion
        }

```

2021-05-10 09:33 UTC, dvdmunckhof commented
@grigoresc it'd be highly appreciated if you could merge this

2021-05-10 09:38 UTC, dvdmunckhof approved these changes

2021-07-29 12:26 UTC, grigoresc commented
Thank you for your changes!

2021-07-29 12:28 UTC, grigoresc approved these changes

2021-07-29 12:28 UTC, merged